version: '3.8'

services:
  yaml-editor:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./path_to_your_directory:/app/path_to_your_directory
    environment:
      - FLASK_ENV=development
